version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # This activates the Docker-specific configuration
    volumes:
      - ./db:/app/db
    restart: always